config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :users, only: %i[show]
  resources :events do
    resources :charges
    resources :attendances, only: %i[index create]
    resources :pictures, only: %i[show]
  end # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :attendance_send

  belongs_to :user
  belongs_to :event

  def attendance_send
    AttendanceMailer.attendance_email(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date,
            :duration,
            :title,
            :price,
            :location,
            :description,
            presence: true
  validate :start_must_be_before_end_time
  validate :ismultiple_of_5?
  validates :duration, numericality: { only_integer: true }
  validates :title, length: { in: 5..140 }
  validates :description, length: { in: 20..1000 }
  validates :price, inclusion: 1..1000

  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :users, through: :attendances
  has_one_attached :picture
  def start_must_be_before_end_time
    start_date > Time.now
  end

  def ismultiple_of_5?
    unless duration % 5 == 0 && duration > 0
      errors.add(:duration, "shouldn't be 0 and need to be multiple of 5 !")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable # Include default devise modules. Others available are:
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  after_create :welcome_send
  has_many :events, foreign_key: 'admin'
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(
        :first_name,
        :last_name,
        :email,
        :description,
        :password,
        :password_confirmation
      )
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index; end

  def create; end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = Event.find_by(id: params[:event_id])
    @price = @event.price
  end

  def create
    @event = Event.find_by(id: params[:event_id])
    @price = @event.price
    amount = @price * 100

    # if is_a?(@event)
    #   Attendance.create(user_id: current_user.id, event_id: @event.id)
    #   redirect_to event_path(@event.id)
    # else
    customer =
      Stripe::Customer.create(
        { email: params[:stripeEmail], source: params[:stripeToken] }
      )

    charge =
      Stripe::Charge.create(
        {
          customer: customer.id,
          amount: amount,
          description: 'Rails Stripe customer',
          currency: 'usd'
        }
      )

    if customer.save && charge.save
      Attendance.create(
        event_id: @event.id,
        user_id: current_user.id,
        stripe_customer_id: customer.id
      )
      redirect_to event_path(@event.id)
    else
      render 'new'
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end # Amount in cents # Amount in cents
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event =
      Event.create(
        start_date: params[:start_date],
        duration: params[:duration],
        title: params[:title],
        description: params[:description],
        price: params[:price],
        location: params[:location],
        admin_id: current_user.id
      )
    @event.picture.attach(params[:picture])
    if @event.save
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def edit; end

  def update; end

  def destroy; end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.picture.attach(params[:picture_id])
    redirect_to new_event_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :good_user
  def good_user
    redirect_to root_path unless current_user == User.find(params[:id])
  end

  def index
    @user = User.all
  end

  def new; end

  def show
    @userfind = User.find(params[:id])
    current_user
  end

  def create; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%=@price%></strong>!</h2>

app/views/charges/new.html.erb
<main role="main ">
    <section class="jumbotron text-center ">


<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Somme à payer : <%= @price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @price %>"
          data-locale="auto"></script>
<% end %>
    </section>

    </main>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="container">
<% unless current_user.present? %>
<h1 class="text-dark py-5 text-center">Welcome </h1>
<h1 class="text-dark py-5 text-center">please subcrib or logging you to see our beatiful website <br> The Event Brite !</h1>
      <% else %>
    <h1 class="text-dark py-5 text-center">Welcome <%=current_user.first_name%> </h1>

  <div class="d-flex mt-4">
    <h4 class="text-dark py-5 mx-auto">Voici la liste des events publié :</h4>
  </div>
  
    <div class="row justify-content-center">  
      <% if @events  &&  current_user.present?%>
      <% @events.each do |event| %>
      <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
          <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <!-- Card content -->
        <div class="card-body">
           <h4 class="card-title">
            <%= truncate(event.title, length: 50) %></h4>
          </div>
          <!-- Title -->
          
          
          <!-- Text -->
           <p class="card-text"><%= truncate(event.description, length: 100) %></p>
          <!-- Button -->
            <%= link_to  "En lire plus", event_path(event.id) %>

        </div>
      </div>
      <% end %>
      
      <% else %>
        <p>Il n'y a pas d'event à venir'</p>
      <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-6 offset-md-3">
    <h1 class="h3 mb-3 font-weight-normal ">Créer event</h1>
   <%= form_tag events_path, multipart: true do %>

	<%= label_tag 'Title' %>
	<%= text_field_tag 'title', @event.title, placeholder: "Your title", class: "form-control mb-3" %>

	<%= label_tag 'Start date' %>
	<%= text_field_tag 'start_date', @event.start_date, placeholder: "Exemple: 2020/06/12 12:00:00", class: "form-control mb-4" %>

	<%= label_tag 'Duration' %>
	<%= text_field_tag 'duration', @event.duration, placeholder: "Duration must be a multiple of 5", class: "form-control mb-4" %>

	<%= label_tag 'Description' %>
	<%= text_area_tag 'description', @event.description, placeholder: "A short description of your event", class: "form-control mb-4" %>

	<%= label_tag 'Price' %>
	<%= text_field_tag 'price', @event.price, placeholder: "Price in euros (without the € sign)", class: "form-control mb-4" %>

	<%= label_tag 'Location' %>
	<%= text_field_tag 'location', @event.location, placeholder: "Address of the event", class: "form-control mb-4" %>

	<%= label_tag 'picture' %>
	<%= file_field_tag :picture %>
	<br/><br/>

	<%= submit_tag "Create event", class: "btn btn-primary" %>
	<% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<main role="main ">

    <section class="jumbotron ">
        <h1 class="jumbotron-heading text-center"><%=@event.title%></h1>
        <p class="lead text-muted">Information personnelles :</p>
   <%if @event.picture.attached?%>     
  <%= image_tag @event.picture, alt: 'picture' %>
<% end%>

        <ul class="list-group list-group-flush">
<li class="list-group-item">Administrateur : <%=@event.admin[:first_name]%></li>
<li class="list-group-item"><i class="far fa-clock">  : Le <%=@event.start_date.strftime('%d/%m/%Y')%></i></li>
<li class="list-group-item"><i class="fas fa-hourglass-half"></i> : <%=@event.duration%> minutes</li>
<li class="list-group-item"><i class="fas fa-stream"></i> : <%=@event.description%></li>
<li class="list-group-item"><i class="fas fa-map-marker-alt"></i> : <%=@event.location%></li>
<li class="list-group-item"><i class="fas fa-euro-sign"></i> : <%=@event.price%> €</li>
<% if current_user != @event.admin%>
<%= link_to "S'inscrire à l'event", new_event_charge_path(params[:id]), class:"btn btn-info text-white" %>
<% end%>

</ul>
    </section>
    
    </main>

    <footer class="text-muted">
    <div class="container">
        <p class="float-right">
        <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; taking on Bootstrap,and customize by Jonathan
        <a href="https://desolate-bayou-88355.herokuapp.com/">Visit the homepage</a> or read our <a href="https://github.com/piwiit/eventbrite_d2">getting started guide</a>.</p>
    </div>
    </footer>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite by THP</title>
    <link rel="icon" href="https://lh3.googleusercontent.com/proxy/luf7HvO4T-6Jp_HL9oLXvDSqTF9aICvFdpsidjdsAuVN3GlN9QhbhGpVQ3vuwftTdJLnh6uEbftGvtkjwkNYYgRKwY7L-Nd93TL9MMLgkE1UuEscodb_d1VGYpEKxlY" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
 <link href="https://fonts.googleapis.com/css2?family=Grandstander:ital,wght@1,300&family=Roboto+Mono:ital,wght@0,400;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/25d75193a7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <header>

      <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="https://i.postimg.cc/Tw6fHCc7/G.png" width="50" height="50" class="d-inline-block align-center" alt="">
        Eventbrite by THP</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        <% unless current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPages" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              S'inscrire / Se connecter
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPages">
              <%= link_to "S'inscrire", new_user_registration_path,class:"dropdown-item" %>
              <%= link_to "Se connecter", new_user_session_path,class:"dropdown-item"%>
            </div>
        <% else %>
         <li class="nav-item mx-auto">
            <%= link_to "Créer un événement", new_event_path, :class =>"nav-link" %>
          </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPages" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPages">
            <%= link_to "Mon profil", user_path(current_user.id), class:"dropdown-item" %><br>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete , class:"dropdown-item"%>
          </div>
          </li>
        <% end %>

        </ul>
      </div>
    </div>
  </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<main role="main ">

    <section class="jumbotron ">
        <h1 class="jumbotron-heading text-center">Profile de <%=current_user.first_name%></h1>
        <p class="lead text-muted">Information personnelles :</p>
        <ul class="list-group list-group-flush">
<li class="list-group-item">Nom : <%=current_user.last_name%></li>
<li class="list-group-item">Prénom : <%=current_user.first_name%></li>
<li class="list-group-item"><i class="fas fa-paper-plane"></i> : <%=current_user.email%></li>
<li class="list-group-item"><i class="fas fa-stream"></i> : <%=current_user.description%></li>
</ul>
    </section>

    <div class="row justify-content-center">
  <% @userfind.events.each do |t| %>
      <div class="card m-4 col-sm-12 col-md-4 col-lg-3 text-center">
        <div class="card-body">
          <h5 class="card-title">
            <%= t.title %><br/><br/>
          </h5>
          <p class="card-text">
            <%= t.duration %> minutes<br/><br/>
            <%= t.start_date.strftime('%d/%m/%Y') %><br/><br/>
            <%= t.price %>€<br/><br/>
            <%= t.location %><br/><br/>
            <%= t.description %><br/><br/>
            <%= link_to "#{t.attendances.count} participant(s)", event_path(t.id), :class =>"btn btn-outline-info"  %><br/> <br/>
          </p>
        </div>
      </div>
      <% end %>
    </div>

    </main>

    <footer class="text-muted">
    <div class="container">
        <p class="float-right">
        <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; taking on Bootstrap,and customize by Jonathan
        <a href="https://desolate-bayou-88355.herokuapp.com/">Visit the homepage</a> or read our <a href="https://github.com/piwiit/eventbrite_d2">getting started guide</a>.</p>
    </div>
    </footer>